services:
  postgres:
    image: postgres:15-alpine
    container_name: securepaste_postgres
    restart: always
    environment:
      POSTGRES_USER: securepaste_user
      POSTGRES_PASSWORD: securepaste_password
      POSTGRES_DB: securepaste_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    container_name: securepaste_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
